### PR TITLE
Plugin gui interface

### PR DESCRIPTION
**Pull request by karimnaaji**
Redesign interface for a better flow in styling and filter creation.

- Each styling filter now has its own view on the builder options, layer and material
- Serialization of the filter styling is now working properly
- Remove unnecessary fields showing up by default from `MapzenScript` script

Part of #20 

screen shot 2017-08-11 at 14 12 40

### CODE REVIEW

**Comment by tallytalwar** [comment]
Going to merge this for now and will add my suggestion above in another PR.

**Comment by matteblair** [comment]
Looks like the editor GUI crashes pretty hard if I generate map data and then play the scene. The Map component ended up in a state where I couldn't use it unless I created a new gameobject or git reset the scene.
screen shot 2017-08-15 at 6 17 27 pm

**Comment by tallytalwar** [comment]
I can not reliably reproduce this. So far only once!

Also the Editor should not reset its state when you render the downloaded game object.

**Comment by matteblair** [comment]
Reproduced the crash again, stack trace here:
```
ArgumentNullException: Argument cannot be null.
Parameter name: key
System.Collections.Generic.Dictionary`2[System.String,System.Boolean].set_Item (System.String key, Boolean value) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:155)
FeatureStyleEditor.LoadPreferences (.MapzenMap mapzenMap) (at Assets/Editor/FeatureStyleEditor.cs:32)
FeatureStyleEditor.OnInspectorGUI (.MapzenMap mapzenMap) (at Assets/Editor/FeatureStyleEditor.cs:50)
MapzenMapEditor.OnInspectorGUI () (at Assets/Editor/MapzenMapEditor.cs:19)
UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor editor, Int32 editorIndex, Boolean rebuildOptimizedGUIBlock, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1229)
UnityEditor.DockArea:OnGUI()
```

**Comment by karimnaaji** [comment]
The issue is fixed in https://github.com/tangrams/tangram-unity/commit/4a24ceb2dfe24c2e37d94dfce36a1f664ec5e607. Thanks for checking this out!

**Pull request merged**
