### PR TITLE
Support for WebGL builds

### PR DESCRIPTION
**Pull request by karimnaaji**
Emscripten flags in Unity WebGL builds are not modifiable and are not defaulting to use c++11 in the build pipeline. To solve that, generate bytecode manually (Added CMake and instructions to do so) for the native library and deactivate threading; using anything under `System.Threading`  wouldn't work for JS. The bytecode is then located under `Assets/Plugins` and will automatically be picked for those builds.

Edit: Emscripten toolchain file from https://github.com/kripken/emscripten/blob/master/cmake/Modules/Platform/Emscripten.cmake.

### CODE REVIEW

**Comment by karimnaaji** [comment]
That's a good idea, I think it's possible to allow that.

**Comment by matteblair** [comment]
Well I've found two problems with the coroutine idea: 1. Coroutines are associated with a MonoBehaviour, so our AsyncWorker would need a new reference to a MonoBehaviour object to call StartCoroutine and 2. Invoking a single task without delay isn't really a pattern that Coroutines help with,  and we're already doing it within the Coroutine for the web request.

I'd say we can skip Coroutines here for now.

**Comment by matteblair** [comment]
I've also noticed that there is a *substantial* drop-off in the performance of AsyncWorker with increasing numbers of threads. Running with 2 workers threads or even 1 worker thread is much faster than with 4.

**Comment by karimnaaji** [comment]
Yes, yesterday I was playing with those values too, at some point I was thinking of getting the ideal thread count using https://msdn.microsoft.com/en-us/library/system.environment.processorcount.aspx, but this seems pointless since we would  instead need the number of cores; though, even with the number of cores, it's hard to tell since Unity probably already uses several threads under the hood, so trying different numbers seems to be the best approach.

**Comment by tallytalwar** [comment]
A general thumb rule for number of threads to use is twice the number of cores. Anything more increases the chances of thrashing. But we are unaware of how many and how threads are being used in Unity's internals.

**Pull request merged**
