### PR TITLE
Build vector tile range on worker threads

### PR DESCRIPTION
**Pull request by karimnaaji**
First iteration towards vector tile mesh generation:
- Move geoJSON parsing and tessellate the features on worker threads
- Build with a fixed range of tile ids that would in the future interact more nicely with the view

LibTessDotNet happens to not be entirely thread safe, which was quite misleading since I first thought that the threading context could be bound to the `Tess` object whenever you create a new instance like `var tess = new Tess();`. There happens to be a `static` storage variable sitting in some pool utilities within the library, this issue should be fixed by https://github.com/karimnaaji/LibTessDotNet/pull/2. This new version is now the version built and used as a `.dll` in this PR, (we might have to maintain our own fork of this library?).

There will be a need for subsequent PR to cleanup URL network handling and create a proper generic interface for it.

### CODE REVIEW

**Comment by matteblair** [comment]
Reviewing! It's unfortunate that LibTessDotNet is not currently thread-safe, that doesn't bode well for the design of the library. The Mapbox Unity SDK found another triangulation library: https://github.com/mapbox/triangle.net-uwp/tree/master so that's another option. I also think it may be worthwhile to write a C# wrapper on a native triangulation library like libtess2 or earcut, since this part of the pipeline is likely to be a very hot path.

**Comment by tallytalwar** [comment]
> since this part of the pipeline is likely to be a very hot path.
I would incline towards going native instead of writing a wrapper. Since from @karimnaaji 's experiments before, using a native lib should be a lot of trouble (other than bundling for all supported platforms).

**Comment by karimnaaji** [comment]
Yes I was looking at this option this morning, their documentation is here https://triangle.codeplex.com/documentation. The LibTessDotNet used in this PR is thread safe, but I would rather move away from it for performance reason anyway.

**Comment by matteblair** [comment]
@karimnaaji I can't currently build the project, I get the error:
```
Assets/Builder.cs(3,7): error CS0246: The type or namespace name `LibTessDotNet' could not be found. Are you missing an assembly reference?
```
Maybe something about the project configuration isn't tracked in git?

**Comment by matteblair** [comment]
I converted indentation in the new files to tabs. Personally I prefer 2-space indentation, but we had been using tabs before and that seems to be the convention for C# Unity projects.

**Pull request merged**
